# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run the tests.
# Adapted from https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Node.js CI

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

env:
  TOKEN_KEY: test_token_key
  TOKEN_EXPIRY_DAYS: 365

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
